# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(auto_created=True, db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('author_name', models.CharField(default='@', max_length=100)),
                ('author_link', models.CharField(default='@', max_length=100)),
                ('author_image', models.URLField(default='')),
                ('date', models.DateTimeField()),
                ('message', models.TextField()),
            ],
        ),
    ]
