# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('created_at', models.DateTimeField()),
                ('favorite_count', models.IntegerField()),
                ('id_tweet', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('id_tweet_str', models.CharField(max_length=2000)),
                ('lang', models.CharField(max_length=2000)),
                ('retweet_count', models.IntegerField()),
                ('source', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=3000)),
                ('expanded_url', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='UserMention',
            fields=[
                ('id_url', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('screen_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('tweet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='top_twitter.Tweet')),
                ('created_at', models.DateTimeField()),
                ('description', models.TextField()),
                ('favourites_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
                ('friends_count', models.IntegerField()),
                ('geo_enabled', models.BooleanField()),
                ('id_user', models.IntegerField()),
                ('lang', models.CharField(max_length=3000)),
                ('listed_count', models.IntegerField()),
                ('location', models.CharField(max_length=3000)),
                ('name', models.CharField(max_length=3000)),
                ('profile_background_color', models.CharField(max_length=3000)),
                ('profile_background_image_url', models.CharField(max_length=3000)),
                ('profile_background_tile', models.CharField(max_length=3000)),
                ('profile_banner_url', models.CharField(max_length=3000)),
                ('profile_image_url', models.CharField(max_length=3000)),
                ('profile_link_color', models.CharField(max_length=3000)),
                ('profile_sidebar_fill_color', models.CharField(max_length=3000)),
                ('profile_text_color', models.CharField(max_length=3000)),
                ('screen_name', models.CharField(max_length=3000)),
                ('statuses_count', models.CharField(max_length=3000)),
                ('time_zone', models.CharField(max_length=3000)),
                ('url', models.CharField(max_length=3000)),
                ('utc_offset', models.IntegerField()),
                ('verified', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='usermention',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top_twitter.Tweet'),
        ),
        migrations.AddField(
            model_name='url',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top_twitter.Tweet'),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top_twitter.Tweet'),
        ),
    ]
