# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top_twitter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='id_tweet',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='id_tweet_str',
            new_name='id_str',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id_user',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='usermention',
            old_name='id_url',
            new_name='id',
        ),
    ]
