# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 22:38
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.IntegerField(auto_created=True, db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('article', models.TextField(default='')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('link_source', models.CharField(default='', max_length=200, validators=[django.core.validators.URLValidator()])),
                ('link_apk', models.CharField(default='', max_length=200, validators=[django.core.validators.URLValidator()])),
                ('preview_image', models.ImageField(default='', help_text='Preview image. Only 1600x800 allowed', upload_to='uploads/images/previews/')),
                ('icon', models.ImageField(default='', help_text='Small icon', upload_to='uploads/images/icons/')),
                ('color_primary', models.CharField(default='#000000', max_length=7)),
                ('color_secondary', models.CharField(default='#000000', max_length=7)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='uploads/images/screenshots')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.App')),
            ],
        ),
    ]
